configfilepath: /Users/kaanyagci/Documents/makepad/scraping.house/.concom.yml
path: /Users/kaanyagci/Documents/makepad/scraping.house
version: ''
scopes:
  - name: auth
    description: All changes related to authentication
  - name: logging
    description: All changes related logging
  - name: profile
    description: All changes realted to profile module
  - name: group
    description: all changes related to group module
  - name: company
    description: All changes related to company module
  - name: config
    description: All changes related configuration
  - name: dependencies
    description: All changes related dependencies
  - name: selectors
    description: All changes related to selectors
  - name: models
    description: All changes related to models
  - name: example
    description: All changes related to the example code
  - name: modules
    description: All changes related modules
  - name: helpers
    description: All changes related to the helper functions
  - name: core
    description: All changes related to the core modules files in general way
  - name: cli
    description: All changes related to the CLI module
  - name: linked
    description: All changes related to the linked module
  - name: common
    description: All changed related to the common package
  - name: docs
    description: All changes related docs folder
conventions:
  - name: build
    description: Changes that affect the build system or external dependencies
  - name: ci
    description: Changes to our CI configuration files and scripts
  - name: docs
    description: Documentation only changes
  - name: feat
    description: A new feature
  - name: revert
    description: 'If the commit reverts a previous commit, it should begin with revert: , followed by the header of the reverted commit. In the body it should say: This reverts commit <hash>., where the hash is the SHA of the commit being reverted.'
  - name: fix
    description: A bug fix
  - name: perf
    description: A code change that improves performance
  - name: refactor
    description: A code change that neither fixes a bug nor adds a feature
  - name: style
    description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
  - name: test
    description: Adding missing tests or correcting existing tests
