export default {
  login: {
    username: '//*[@id="session_key"]',
    password: '//*[@id="session_password"]',
    submit: '//button[contains(@class,"sign-in-form__submit-button")]',
  },
  user: {
    profile: {
      base: {
        fullName: "//div[contains(@class,'pv-text-details__left-panel')][1]/div[1]/h1",
        shortDesc: "//div[contains(@class,'pv-text-details__left-panel')][1]/div[2]",
        location: "//div[contains(@class,'pv-text-details__left-panel')][2]/span[1]",
        info: "//section[contains(@class,'pv-about-section')]/div",
        infoTextToDelete: "//section[contains(@class,'pv-about-section')]/div/span",
        premiumBadge: "//li-icon[@type='linkedin-bug']",
        influencerBadge: "//li-icon[@type='linkedin-influencer-color-icon']",
      },
      experience: {
        item: "//li[contains(@class,'pv-entity__position-group-role-item')]",
        group: "//section[@id='experience-section']//li[contains(@class,'pv-entity__position-group-pager')]",
        moreButton: "//section[@id='experience-section']//div[contains(@class,'pv-experience-section__see-more')]//li-icon[@type='chevron-down-icon']/parent::button",
        roleContainer: "//div[@class='pv-entity__role-container']",
        expandRoles: "//div[contains(@class,'pv-entity__paging')]//li-icon[@type='chevron-down-icon']/parent::button",
        groupTitle: "//div[contains(@class,'pv-entity__company-summary-info')]/h3/span[2]",
        groupSubTitle: "//div[contains(@class,'pv-entity__company-summary-info')]/h4/span[2]",
        roleName: "//div[contains(@class,'pv-entity__summary-info-v2')]/h3//span[2]",
        roleInfo: "//div[contains(@class,'pv-entity__summary-info-v2')]//h4//span[2]",
        contratType: "//div[contains(@class,'pv-entity__summary-info-v2')]/h3/following-sibling::h4[not(contains(@class,'pv-entity__location'))]",
        roleDescription: "//div[contains(@class,'pv-entity__extra-details')]/div[contains(@class,'inline-show-more-text')]",
        roleDescriptionMore: "/span[contains(@class,'inline-show-more-text__link-container-collapsed')]",
        summary: "//div[contains(@class,'pv-entity__summary-info')]",
        location: "//h4[contains(@class,'pv-entity__location')]/span[2]",
        description: "//div[contains(@class,'pv-entity__extra-details')]/div[contains(@class, 'inline-show-more-text')]",
        duration: '//h4[2]/span[2]',
        timeInterval: "//h4[contains(@class,'pv-entity__date-range')]/span[2]",
        companyName: '/p[2]',
      },
      education: {
        section: "//section[contains(@id,'education-section')]",
        elementsContainer: "/ul[contains(@class,'pv-profile-section__section-info')]",
        seeMoreButton: "//div[contains(@class,'pv-profile-section__actions-inline')]//li-icon[@type='chevron-down-icon']/parent::button",
        listItem: "//li[contains(@class,'pv-education-entity')]",
        schoolName: "//h3[contains(@class,'pv-entity__school-name')]",
        entitySecondaryTitle: "//p[contains(@class,'pv-entity__secondary-title')]",
        fieldName: "//p[contains(@class,'pv-entity__fos')]/span[2]",
        degreeName: "//p[contains(@class,'pv-entity__degree-name')]/span[2]",
        date: "//p[contains(@class,'pv-entity__dates')]//span[2]",
        description: "//p[contains(@class,'pv-entity__description')]/span[2]",
        activitiesAndSocieties: "//span[contains(@class,'activities-societies')]",
      },
    },
  },
};
